Fix NoClassDefFoundError: com/google/inject/AbstractModule in pulsar-io/batch-data-generator and Jcloud offloader (#14150)
(cherry picked from commit 25ccf45fcaa71d97cae26244a6b7dfca75a4a089)